name: Android Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autotools-dev libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Forzamos la versión del NDK en el archivo de configuración antes de empezar
          sed -i 's/^[# ]*android.ndk =.*/android.ndk = 25b/' buildozer.spec
          sed -i 's/^[# ]*android.api =.*/android.api = 33/' buildozer.spec
          # Limpiamos basura de intentos fallidos
          rm -rf .buildozer/android/platform/android-ndk-r28c
          yes | buildozer -v android debug
